services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    PimcoreValidationBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Controller/'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    PimcoreValidationBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    PimcoreValidationBundle\Installer:
        arguments:
            $bundle: '@PimcoreValidationBundle\PimcoreValidationBundle'
        public: true

# add more services, or override services that need manual wiring
#    PimcoreValidationBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
